title: 'Daniel "Dan" Boles — AI & Systems'
description: Researchâ†’Code workflows with contracts, tests, CI, and reproducible artifacts.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# nav items (appear in the header)
navigation:
  - title: Projects
    url: /
  - title: GitHub
    url: https://github.com/dboles99
  - title: Resume
    url: /assets/DanBoles_Resume.pdf

# social (used by the head include below)
social:
  github: dboles99
  linkedin: YOUR-LINKEDIN-SLUG
  email: your@email.tld